In [2]:
import torch

## 创建Tensor

### Create a tensor with random values

In [3]:
torch.rand(2, 3, 4) # 2x3x4 tensor with random values

tensor([[[0.8039, 0.2681, 0.1221, 0.1207],
         [0.6013, 0.6913, 0.1132, 0.1190],
         [0.9707, 0.6881, 0.3528, 0.8793]],

        [[0.9501, 0.9489, 0.7698, 0.1679],
         [0.5540, 0.3775, 0.6944, 0.0947],
         [0.7737, 0.9595, 0.4570, 0.4725]]])

### Create a tensor with all zeros

In [4]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

### Create a tensor with all ones

In [5]:
# 2 * 3 * 4 tensor with all ones

torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### Create a tensor from a list

In [6]:
# create a tensor from a list

x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Tensor的形状需要合规

In [7]:
x = torch.Tensor([[1, 2, 3], [4, 5]]) # error

ValueError: expected sequence of length 3 at dim 1 (got 2)

In [ ]:
# create a tensor from a numpy array

import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = torch.from_numpy(x)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


### 通过Reshape的方式创建Tensor

In [ ]:
# create a tensor by reshaping

torch.arange(0, 12).reshape(2, 3, 2)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

## Tensor的运算

In [ ]:
# 所有的元素加一

torch.ones(2, 3) + 1

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [ ]:
# multiply a tensor by a scalar

torch.ones(2, 3) * 2.3

tensor([[2.3000, 2.3000, 2.3000],
        [2.3000, 2.3000, 2.3000]])

## Tensor的切片
访问Tensor的部分元素

In [ ]:
# create a 4 * 4 * 3 tensor with random numbers
# simulate a 4 * 4 image with 3 channels

# set random seed to 42
torch.manual_seed(42)

x = torch.rand(4, 4, 3)
print(x)

tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408],
         [0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547],
         [0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890],
         [0.2814, 0.7886, 0.5895]]])


In [ ]:
# 找到图片所有的R值

x[:, :, 0] # all rows, all columns, first channel

tensor([[0.8823, 0.9593, 0.2566, 0.1332],
        [0.8694, 0.4294, 0.2666, 0.4414],
        [0.1053, 0.1994, 0.9516, 0.5832],
        [0.5779, 0.3423, 0.7104, 0.2814]])

In [ ]:
# 找到图片所有的G值

x[:, :, 1] # all rows, all columns, second channel

tensor([[0.9150, 0.3904, 0.7936, 0.9346],
        [0.5677, 0.8854, 0.6274, 0.2969],
        [0.2695, 0.5472, 0.0753, 0.3376],
        [0.9040, 0.6343, 0.9464, 0.7886]])

In [ ]:
# 找到图片所有的B值

x[:, :, 2] # all rows, all columns, third channel

tensor([[0.3829, 0.6009, 0.9408, 0.5936],
        [0.7411, 0.5739, 0.2696, 0.8317],
        [0.3588, 0.0062, 0.8860, 0.8090],
        [0.5547, 0.3644, 0.7890, 0.5895]])

In [ ]:
# 找到图片所有的R和G值

x[:, :, 0:2] # all rows, all columns, first and second channel

tensor([[[0.8823, 0.9150],
         [0.9593, 0.3904],
         [0.2566, 0.7936],
         [0.1332, 0.9346]],

        [[0.8694, 0.5677],
         [0.4294, 0.8854],
         [0.2666, 0.6274],
         [0.4414, 0.2969]],

        [[0.1053, 0.2695],
         [0.1994, 0.5472],
         [0.9516, 0.0753],
         [0.5832, 0.3376]],

        [[0.5779, 0.9040],
         [0.3423, 0.6343],
         [0.7104, 0.9464],
         [0.2814, 0.7886]]])

In [ ]:
# 找到图片左上角的2 * 2区域
x[0:2, 0:2, :] # first two rows, first two columns, all channels

tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]],

        [[0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]]])

In [ ]:
x[0:2, 0:2, :] = 1 
# set the values of the first two rows, first two columns, all channels to 1

In [ ]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## 矩阵的乘法

In [10]:
# 创建一个张量 tensor [1, 2, 3]
x = torch.tensor([1, 2, 3, 4])
print(x * x)

print(torch.matmul(x, x))

tensor([ 1,  4,  9, 16])
tensor(30)


In [13]:
y = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(y * y)
print(torch.matmul(y, y))

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [14]:
print(x * y)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1